//
// sk_app - X11 symbols resolved at runtime
//
// Expanded several times with different definitions of the per-library
// SKA_*_SYM macros, so each symbol is written once and the pointer, its
// type, and the dlsym call cannot drift apart.
// Deliberately has no include guard.

SKA_X11_SYM(XAllocClassHint)
SKA_X11_SYM(XAllocSizeHints)
SKA_X11_SYM(XChangeProperty)
SKA_X11_SYM(XCheckIfEvent)
SKA_X11_SYM(XCheckTypedWindowEvent)
SKA_X11_SYM(XCloseDisplay)
SKA_X11_SYM(XCloseIM)
SKA_X11_SYM(XConvertSelection)
SKA_X11_SYM(XCreateBitmapFromData)
SKA_X11_SYM(XCreateColormap)
SKA_X11_SYM(XFreeColormap)
SKA_X11_SYM(XCreateFontCursor)
SKA_X11_SYM(XCreateIC)
SKA_X11_SYM(XCreatePixmapCursor)
SKA_X11_SYM(XCreateWindow)
SKA_XCURSOR_SYM(XcursorLibraryLoadCursor)
SKA_X11_SYM(XDefineCursor)
SKA_X11_SYM(XDeleteProperty)
SKA_X11_SYM(XDestroyIC)
SKA_X11_SYM(XDestroyWindow)
SKA_X11_SYM(XFilterEvent)
SKA_X11_SYM(XFlush)
SKA_X11_SYM(XFree)
SKA_X11_SYM(XFreePixmap)
SKA_X11_SYM(XGetSelectionOwner)
SKA_X11_SYM(XGetWindowAttributes)
SKA_X11_SYM(XGetWindowProperty)
SKA_X11_SYM(XIconifyWindow)
SKA_X11_SYM(XInternAtom)
SKA_X11_SYM(XkbSetDetectableAutoRepeat)
SKA_X11_SYM(XLookupKeysym)
SKA_X11_SYM(XMapWindow)
SKA_X11_SYM(XMoveWindow)
SKA_X11_SYM(XNextEvent)
SKA_X11_SYM(XOpenDisplay)
SKA_X11_SYM(XOpenIM)
SKA_X11_SYM(XPending)
SKA_X11_SYM(XQueryPointer)
SKA_X11_SYM(XRaiseWindow)
SKA_X11_SYM(XResizeWindow)
SKA_X11_SYM(XResourceManagerString)
SKA_X11_SYM(XrmDestroyDatabase)
SKA_X11_SYM(XrmGetResource)
SKA_X11_SYM(XrmGetStringDatabase)
SKA_X11_SYM(XrmInitialize)
SKA_XRANDR_SYM(XRRConfigCurrentRate)
SKA_XRANDR_SYM(XRRFreeScreenConfigInfo)
SKA_XRANDR_SYM(XRRGetScreenInfo)
SKA_X11_SYM(XSelectInput)
SKA_X11_SYM(XSendEvent)
SKA_X11_SYM(XSetClassHint)
SKA_X11_SYM(XSetICFocus)
SKA_X11_SYM(XSetIconName)
SKA_X11_SYM(XSetInputFocus)
SKA_X11_SYM(XSetLocaleModifiers)
SKA_X11_SYM(XSetSelectionOwner)
SKA_X11_SYM(XSetWMNormalHints)
SKA_X11_SYM(XSetWMProtocols)
SKA_X11_SYM(XStoreName)
SKA_X11_SYM(XSync)
SKA_X11_SYM(XTranslateCoordinates)
SKA_X11_SYM(XUnmapWindow)
SKA_X11_SYM(XUnsetICFocus)
SKA_X11_SYM(XWarpPointer)
SKA_X11_SYM(Xutf8LookupString)

// XInput2 raw motion, the only unaccelerated pointer source X11 offers
SKA_X11_SYM(XQueryExtension)
SKA_X11_SYM(XGetEventData)
SKA_X11_SYM(XFreeEventData)
SKA_X11_SYM(XGrabPointer)
SKA_X11_SYM(XUngrabPointer)
SKA_XI2_SYM(XIQueryVersion)
SKA_XI2_SYM(XISelectEvents)

// XSync counters, for the _NET_WM_SYNC_REQUEST resize handshake
SKA_XEXT_SYM(XSyncQueryExtension)
SKA_XEXT_SYM(XSyncInitialize)
SKA_XEXT_SYM(XSyncCreateCounter)
SKA_XEXT_SYM(XSyncSetCounter)
SKA_XEXT_SYM(XSyncDestroyCounter)
